[project]
name = "pycompool"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fire>=0.7.0",
    "pyserial>=3.5",
    "serial>=0.0.97",
]
